bump script: automate up to pushing the tag

diff --git a/bin/bump b/bin/bump
--- a/bin/bump
+++ b/bin/bump
@@ -2,4 +2,44 @@
 
 set -eo pipefail
 
-uv version --bump $@
+fail() {
+  echo "$@" 1>&2;
+  exit 1
+}
+
+main() {
+    local current_branch=
+	current_branch=$(git rev-parse --abbrev-ref HEAD)
+	if [[ ${current_branch} != "main" ]]; then
+	  fail "error: Must be on main to release; git checkout main"
+	fi
+
+    local current_version=
+    current_version=$(uv version --short)
+    echo "Current version is ${current_version}"
+
+    local new_version=$1
+    if [[ -z "${new_version}" ]]; then
+        fail "Please specify the new version!"
+    fi
+
+	if ! (python -c "from packaging import version; assert version.parse('${new_version}') > version.parse('${current_version}')" 2> /dev/null); then
+	  fail "error: version must be greater than ${current_version}"
+	fi
+
+	read -p "Release ${version}? [y/n]" -n 1 -r
+	echo
+	if [[ $REPLY =~ ^[Yy]$ ]]; then
+	    poetry version "${version}"
+        uv version ${new_version}
+
+		git reset -- ${ROOT_DIR}
+		git add "${ROOT_DIR}/pyproject.toml"
+		git commit -m "version: release ${version}"
+		git push
+
+	    echo "Release at https://github.com/Flared/python-flareio/releases/new?tag=v${version}&target=main&title=v${version}"
+	fi
+}
+
+main $@
