bin: formating + check version

diff --git a/bin/bump b/bin/bump
--- a/bin/bump
+++ b/bin/bump
@@ -12,10 +12,10 @@ fail() {
 
 main() {
     local current_branch=
-	current_branch=$(git rev-parse --abbrev-ref HEAD)
-	if [[ ${current_branch} != "main" ]]; then
-	  fail "error: Must be on main to release; git checkout main"
-	fi
+    current_branch=$(git rev-parse --abbrev-ref HEAD)
+    if [[ ${current_branch} != "main" ]]; then
+        fail "error: Must be on main to release; git checkout main"
+    fi
 
     local current_version=
     current_version=$(uv version --short)
@@ -26,19 +26,23 @@ main() {
         fail "Please specify the new version!"
     fi
 
-	read -p "Release ${version}? [y/n]" -n 1 -r
-	echo
-	if [[ $REPLY =~ ^[Yy]$ ]]; then
+    if ! (python -c "from packaging import version; assert version.parse('${new_version}') > version.parse('${current_version}')" 2> /dev/null); then
+        fail "error: version must be greater than ${current_version}"
+    fi
+
+    read -p "Release ${version}? [y/n]" -n 1 -r
+    echo
+    if [[ $REPLY =~ ^[Yy]$ ]]; then
         uv version ${new_version}
 
-		git reset -- ${ROOT_DIR}
-		git add "${ROOT_DIR}/pyproject.toml"
-		git add "${ROOT_DIR}/uv.lock"
-		git commit -m "version: release ${new_version}"
-		git push
+        git reset -- ${ROOT_DIR}
+        git add "${ROOT_DIR}/pyproject.toml"
+        git add "${ROOT_DIR}/uv.lock"
+        git commit -m "version: release ${new_version}"
+        git push
 
-	    echo "Release at https://github.com/Flared/flareio-cli/releases/new?tag=v${new_version}&target=main&title=v${new_version}"
-	fi
+        echo "Release at https://github.com/Flared/flareio-cli/releases/new?tag=v${new_version}&target=main&title=v${new_version}"
+    fi
 }
 
 main $@
